package com.iocl.customer.model.viewobject;

import java.math.BigDecimal;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 01 12:22:42 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomerGeneralVoRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Srno,
        ConnectionType,
        EquipType,
        HotPlate,
        paymentMode,
        PromoSelected,
        ProofOfIdentityType,
        ProofOfIdentityNo,
        POIDocType,
        ProofOfAddressType,
        ProofOfAddressNo,
        POADocType,
        SubsVouch_ConnVo1,
        YesNo_GeneralVo1,
        LPG_POI_Vo1,
        LPG_POA_Vo1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SRNO = AttributesEnum.Srno.index();
    public static final int CONNECTIONTYPE = AttributesEnum.ConnectionType.index();
    public static final int EQUIPTYPE = AttributesEnum.EquipType.index();
    public static final int HOTPLATE = AttributesEnum.HotPlate.index();
    public static final int PAYMENTMODE = AttributesEnum.paymentMode.index();
    public static final int PROMOSELECTED = AttributesEnum.PromoSelected.index();
    public static final int PROOFOFIDENTITYTYPE = AttributesEnum.ProofOfIdentityType.index();
    public static final int PROOFOFIDENTITYNO = AttributesEnum.ProofOfIdentityNo.index();
    public static final int POIDOCTYPE = AttributesEnum.POIDocType.index();
    public static final int PROOFOFADDRESSTYPE = AttributesEnum.ProofOfAddressType.index();
    public static final int PROOFOFADDRESSNO = AttributesEnum.ProofOfAddressNo.index();
    public static final int POADOCTYPE = AttributesEnum.POADocType.index();
    public static final int SUBSVOUCH_CONNVO1 = AttributesEnum.SubsVouch_ConnVo1.index();
    public static final int YESNO_GENERALVO1 = AttributesEnum.YesNo_GeneralVo1.index();
    public static final int LPG_POI_VO1 = AttributesEnum.LPG_POI_Vo1.index();
    public static final int LPG_POA_VO1 = AttributesEnum.LPG_POA_Vo1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CustomerGeneralVoRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Srno.
     * @return the Srno
     */
    public BigDecimal getSrno() {
        return (BigDecimal) getAttributeInternal(SRNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Srno.
     * @param value value to set the  Srno
     */
    public void setSrno(BigDecimal value) {
        setAttributeInternal(SRNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ConnectionType.
     * @return the ConnectionType
     */
    public String getConnectionType() {
        if (getAttributeInternal(CONNECTIONTYPE) != null) {
            return (String) getAttributeInternal(CONNECTIONTYPE);
        } else {
            return "SBC";
        }

    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ConnectionType.
     * @param value value to set the  ConnectionType
     */
    public void setConnectionType(String value) {
        setAttributeInternal(CONNECTIONTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EquipType.
     * @return the EquipType
     */
    public String getEquipType() {
        if (getAttributeInternal(EQUIPTYPE) != null) {
            return (String) getAttributeInternal(EQUIPTYPE);
        } else {
            return "14.2";
        }

        //
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EquipType.
     * @param value value to set the  EquipType
     */
    public void setEquipType(String value) {
        setAttributeInternal(EQUIPTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HotPlate.
     * @return the HotPlate
     */
    public String getHotPlate() {
        if (getAttributeInternal(HOTPLATE) != null) {
            return (String) getAttributeInternal(HOTPLATE);
        } else {
            return "Y";
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HotPlate.
     * @param value value to set the  HotPlate
     */
    public void setHotPlate(String value) {
        setAttributeInternal(HOTPLATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute paymentMode.
     * @return the paymentMode
     */
    public String getpaymentMode() {
        return (String) getAttributeInternal(PAYMENTMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute paymentMode.
     * @param value value to set the  paymentMode
     */
    public void setpaymentMode(String value) {
        setAttributeInternal(PAYMENTMODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PromoSelected.
     * @return the PromoSelected
     */
    public String getPromoSelected() {
        return (String) getAttributeInternal(PROMOSELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PromoSelected.
     * @param value value to set the  PromoSelected
     */
    public void setPromoSelected(String value) {
        setAttributeInternal(PROMOSELECTED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProofOfIdentityType.
     * @return the ProofOfIdentityType
     */
    public String getProofOfIdentityType() {
        return (String) getAttributeInternal(PROOFOFIDENTITYTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProofOfIdentityType.
     * @param value value to set the  ProofOfIdentityType
     */
    public void setProofOfIdentityType(String value) {
        setAttributeInternal(PROOFOFIDENTITYTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProofOfIdentityNo.
     * @return the ProofOfIdentityNo
     */
    public String getProofOfIdentityNo() {
        return (String) getAttributeInternal(PROOFOFIDENTITYNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProofOfIdentityNo.
     * @param value value to set the  ProofOfIdentityNo
     */
    public void setProofOfIdentityNo(String value) {
        setAttributeInternal(PROOFOFIDENTITYNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProofOfAddressType.
     * @return the ProofOfAddressType
     */
    public String getProofOfAddressType() {
        return (String) getAttributeInternal(PROOFOFADDRESSTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProofOfAddressType.
     * @param value value to set the  ProofOfAddressType
     */
    public void setProofOfAddressType(String value) {
        setAttributeInternal(PROOFOFADDRESSTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProofOfAddressNo.
     * @return the ProofOfAddressNo
     */
    public String getProofOfAddressNo() {
        return (String) getAttributeInternal(PROOFOFADDRESSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProofOfAddressNo.
     * @param value value to set the  ProofOfAddressNo
     */
    public void setProofOfAddressNo(String value) {
        setAttributeInternal(PROOFOFADDRESSNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute POIDocType.
     * @return the POIDocType
     */
    public String getPOIDocType() {
        return (String) getAttributeInternal(POIDOCTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute POIDocType.
     * @param value value to set the  POIDocType
     */
    public void setPOIDocType(String value) {
        setAttributeInternal(POIDOCTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute POADocType.
     * @return the POADocType
     */
    public String getPOADocType() {
        return (String) getAttributeInternal(POADOCTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute POADocType.
     * @param value value to set the  POADocType
     */
    public void setPOADocType(String value) {
        setAttributeInternal(POADOCTYPE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SubsVouch_ConnVo1.
     */
    public RowSet getSubsVouch_ConnVo1() {
        return (RowSet) getAttributeInternal(SUBSVOUCH_CONNVO1);
    }


    /**
     * Gets the view accessor <code>RowSet</code> YesNo_GeneralVo1.
     */
    public RowSet getYesNo_GeneralVo1() {
        return (RowSet) getAttributeInternal(YESNO_GENERALVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LPG_POI_Vo1.
     */
    public RowSet getLPG_POI_Vo1() {
        return (RowSet) getAttributeInternal(LPG_POI_VO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LPG_POA_Vo1.
     */
    public RowSet getLPG_POA_Vo1() {
        return (RowSet) getAttributeInternal(LPG_POA_VO1);
    }
}

