package com.iocl.customer.model.viewobject;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 22 16:30:39 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DealerFeedbackVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Dummy,
        QuantityDelivered,
        Service,
        Cleanliness,
        Facilities,
        CleanToilet;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int DUMMY = AttributesEnum.Dummy.index();
    public static final int QUANTITYDELIVERED = AttributesEnum.QuantityDelivered.index();
    public static final int SERVICE = AttributesEnum.Service.index();
    public static final int CLEANLINESS = AttributesEnum.Cleanliness.index();
    public static final int FACILITIES = AttributesEnum.Facilities.index();
    public static final int CLEANTOILET = AttributesEnum.CleanToilet.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DealerFeedbackVORowImpl() {
    }
}

