package com.iocl.customer.model.viewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 22 16:30:40 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DealerFeedbackVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DealerFeedbackVOImpl() {
    }
}

