package com.iocl.customer.model.viewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 10 16:03:24 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GrievSubCatVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GrievSubCatVOImpl() {
    }
}

