package com.iocl.customer.model.viewobject;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 10 16:33:48 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GrievFormRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Dummy,
        Name,
        MobileNumber,
        EmailId,
        Address,
        Category,
        SubCategory,
        ComplainDetails,
        SubcatCount,
        GrievCatVO1,
        GrievSubCatVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DUMMY = AttributesEnum.Dummy.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int MOBILENUMBER = AttributesEnum.MobileNumber.index();
    public static final int EMAILID = AttributesEnum.EmailId.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int CATEGORY = AttributesEnum.Category.index();
    public static final int SUBCATEGORY = AttributesEnum.SubCategory.index();
    public static final int COMPLAINDETAILS = AttributesEnum.ComplainDetails.index();
    public static final int SUBCATCOUNT = AttributesEnum.SubcatCount.index();
    public static final int GRIEVCATVO1 = AttributesEnum.GrievCatVO1.index();
    public static final int GRIEVSUBCATVO1 = AttributesEnum.GrievSubCatVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GrievFormRowImpl() {
    }
}

