package com.iocl.customer.model.viewobject;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 10 16:01:56 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GrievCatVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CategoryId,
        CategoryGroup,
        CategoryCode,
        Category,
        Description,
        StartDate,
        EndDate,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        SortBy,
        SubcatCount;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int CATEGORYID = AttributesEnum.CategoryId.index();
    public static final int CATEGORYGROUP = AttributesEnum.CategoryGroup.index();
    public static final int CATEGORYCODE = AttributesEnum.CategoryCode.index();
    public static final int CATEGORY = AttributesEnum.Category.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int SORTBY = AttributesEnum.SortBy.index();
    public static final int SUBCATCOUNT = AttributesEnum.SubcatCount.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GrievCatVORowImpl() {
    }
}

