package com.iocl.customer.model.viewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 16 16:18:55 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LPGAreaOfficeMasterVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LPGAreaOfficeMasterVOImpl() {
    }
}

