package com.iocl.customer.model.viewobject;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 12 17:36:22 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LpgDistMasterRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DistName,
        UcmUid,
        SapCode,
        MainPhNum,
        SoldToPartyCode,
        MainEmailAddr,
        Addr,
        AddrLine2,
        AddrLine3,
        AddrLine4,
        State,
        StateName,
        Province,
        Zipcode,
        Longitude,
        Latitude,
        SalesAreaCode,
        SalesAreaName,
        AoCode,
        AoName,
        Dist5kgFtl,
        IvrsNum,
        Sno,
        Distance;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DISTNAME = AttributesEnum.DistName.index();
    public static final int UCMUID = AttributesEnum.UcmUid.index();
    public static final int SAPCODE = AttributesEnum.SapCode.index();
    public static final int MAINPHNUM = AttributesEnum.MainPhNum.index();
    public static final int SOLDTOPARTYCODE = AttributesEnum.SoldToPartyCode.index();
    public static final int MAINEMAILADDR = AttributesEnum.MainEmailAddr.index();
    public static final int ADDR = AttributesEnum.Addr.index();
    public static final int ADDRLINE2 = AttributesEnum.AddrLine2.index();
    public static final int ADDRLINE3 = AttributesEnum.AddrLine3.index();
    public static final int ADDRLINE4 = AttributesEnum.AddrLine4.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int STATENAME = AttributesEnum.StateName.index();
    public static final int PROVINCE = AttributesEnum.Province.index();
    public static final int ZIPCODE = AttributesEnum.Zipcode.index();
    public static final int LONGITUDE = AttributesEnum.Longitude.index();
    public static final int LATITUDE = AttributesEnum.Latitude.index();
    public static final int SALESAREACODE = AttributesEnum.SalesAreaCode.index();
    public static final int SALESAREANAME = AttributesEnum.SalesAreaName.index();
    public static final int AOCODE = AttributesEnum.AoCode.index();
    public static final int AONAME = AttributesEnum.AoName.index();
    public static final int DIST5KGFTL = AttributesEnum.Dist5kgFtl.index();
    public static final int IVRSNUM = AttributesEnum.IvrsNum.index();
    public static final int SNO = AttributesEnum.Sno.index();
    public static final int DISTANCE = AttributesEnum.Distance.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LpgDistMasterRowImpl() {
    }
}

