package com.iocl.customer.model.viewobject;

import java.sql.Timestamp;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 19 15:28:08 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LpgSvcCacheViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        UserId,
        WebServiceId,
        SvcRequest,
        SvcResponse,
        SvcHitTime,
        Status;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int WEBSERVICEID = AttributesEnum.WebServiceId.index();
    public static final int SVCREQUEST = AttributesEnum.SvcRequest.index();
    public static final int SVCRESPONSE = AttributesEnum.SvcResponse.index();
    public static final int SVCHITTIME = AttributesEnum.SvcHitTime.index();
    public static final int STATUS = AttributesEnum.Status.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LpgSvcCacheViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute UserId.
     * @return the UserId
     */
    public String getUserId() {
        return (String) getAttributeInternal(USERID);
    }

    /**
     * Gets the attribute value for the calculated attribute WebServiceId.
     * @return the WebServiceId
     */
    public String getWebServiceId() {
        return (String) getAttributeInternal(WEBSERVICEID);
    }

    /**
     * Gets the attribute value for the calculated attribute SvcRequest.
     * @return the SvcRequest
     */
    public BlobDomain getSvcRequest() {
        return (BlobDomain) getAttributeInternal(SVCREQUEST);
    }

    /**
     * Gets the attribute value for the calculated attribute SvcResponse.
     * @return the SvcResponse
     */
    public BlobDomain getSvcResponse() {
        return (BlobDomain) getAttributeInternal(SVCRESPONSE);
    }

    /**
     * Gets the attribute value for the calculated attribute SvcHitTime.
     * @return the SvcHitTime
     */
    public Timestamp getSvcHitTime() {
        return (Timestamp) getAttributeInternal(SVCHITTIME);
    }

    /**
     * Gets the attribute value for the calculated attribute Status.
     * @return the Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }
}

