package com.iocl.customer.model.viewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 17 14:50:03 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NetworkLocatorVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NetworkLocatorVoImpl() {
    }
}

