package com.iocl.customer.model.viewobject;

import com.iocl.customer.model.service.AppModuleImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 17 14:50:00 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NetworkLocatorVoRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Dummy,
        NetworkType,
        LocationSearch,
        CategoryCode,
        CategoryType,
        LocationCategoryVo1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DUMMY = AttributesEnum.Dummy.index();
    public static final int NETWORKTYPE = AttributesEnum.NetworkType.index();
    public static final int LOCATIONSEARCH = AttributesEnum.LocationSearch.index();
    public static final int CATEGORYCODE = AttributesEnum.CategoryCode.index();
    public static final int CATEGORYTYPE = AttributesEnum.CategoryType.index();
    public static final int LOCATIONCATEGORYVO1 = AttributesEnum.LocationCategoryVo1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NetworkLocatorVoRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Dummy.
     * @return the Dummy
     */
    public String getDummy() {
        return (String) getAttributeInternal(DUMMY);
    }

    /**
     * Gets the attribute value for the calculated attribute NetworkType.
     * @return the NetworkType
     */
    public String getNetworkType() {
//        String val=null;
//        if(this.getCategoryType()!=null){
//            AppModuleImpl amImpl=(AppModuleImpl)this.getApplicationModule();
//            ViewObject locationCategoryVo=amImpl.getLocationCategoryVo1();
//            Row[] rr=locationCategoryVo.getFilteredRows("CategoryType", this.getCategoryType());
//            if(rr.length>0){
//                if (rr[0].getAttribute("CategoryName")!=null) {
//                    val = rr[0].getAttribute("CategoryName").toString();
//                    
//                }
//            }
//        }
//        else{
//            val=(String) getAttributeInternal(NETWORKTYPE);
//        }
        return (String) getAttributeInternal(NETWORKTYPE);
        
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NetworkType.
     * @param value value to set the  NetworkType
     */
    public void setNetworkType(String value) {
        setAttributeInternal(NETWORKTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LocationSearch.
     * @return the LocationSearch
     */
    public String getLocationSearch() {
        return (String) getAttributeInternal(LOCATIONSEARCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LocationSearch.
     * @param value value to set the  LocationSearch
     */
    public void setLocationSearch(String value) {
        setAttributeInternal(LOCATIONSEARCH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryCode.
     * @return the CategoryCode
     */
    public String getCategoryCode() {
        return (String) getAttributeInternal(CATEGORYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CategoryCode.
     * @param value value to set the  CategoryCode
     */
    public void setCategoryCode(String value) {
        setAttributeInternal(CATEGORYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryType.
     * @return the CategoryType
     */
    public String getCategoryType() {
        return (String) getAttributeInternal(CATEGORYTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CategoryType.
     * @param value value to set the  CategoryType
     */
    public void setCategoryType(String value) {
        setAttributeInternal(CATEGORYTYPE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LocationCategoryVo1.
     */
    public RowSet getLocationCategoryVo1() {
        return (RowSet) getAttributeInternal(LOCATIONCATEGORYVO1);
    }
}

