package com.iocl.customer.model.viewobject;

import com.iocl.customer.model.utils.EPICConstant;
import com.iocl.customer.model.utils.EPICIOCLResourceModel;

import ioclcommonproj.com.iocl.utils.JSONArray;
import ioclcommonproj.com.iocl.utils.JSONObject;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;

import org.apache.log4j.Logger;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 19 18:34:58 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PartnerLocatorVOImpl extends ViewObjectImpl {
    
    private static Logger log ;
    
    /**
     * This is the default constructor (do not remove).
     */
    public PartnerLocatorVOImpl() {
        String logFlag = EPICIOCLResourceModel.findKeyValue("LOGS_PRINT_FLAG");
        if (logFlag != null && "Y".equalsIgnoreCase(logFlag)) {

            log = Logger.getLogger(PartnerLocatorVOImpl.class);

        } else {
            log = Logger.getLogger(PartnerLocatorVOImpl.class);
            Logger.getRootLogger().setLevel(org.apache.log4j.Level.OFF);
        }
    }
    
    
    /*
     * Below Method is Used for EPICConstant.CHECK_APPLICATION_STATUS Case 
     * in serviceLPGCall method
     * */
    public void populatePartnerDistributor(String jsonInpString) {
        System.out.println("jsonInpString "+jsonInpString);
        JSONObject jsonObject = new JSONObject(jsonInpString);
        JSONObject jsonResponse = jsonObject.getJSONObject("MapObject");
        JSONArray arrObj =jsonResponse.getJSONArray("VwMobLPGInfo");
        log.info("arrObj "+arrObj);
        this.getViewObject().executeEmptyRowSet();
        for (int i = 0; i < arrObj.length(); i++) {
            JSONObject objOD = arrObj.getJSONObject(i);
            Row row = this.createRow();
            if (!objOD.isNull("SalesAreaName")) {
                row.setAttribute("SalesAreaName", String.valueOf(objOD.get("SalesAreaName")));
            }else{
                row.setAttribute("SalesAreaName", "N.A.");
            }
            if (!objOD.isNull("BreakdownServiceNo")) {
                row.setAttribute("BreakdownServiceNo", String.valueOf(objOD.get("BreakdownServiceNo")));
            }else{
                row.setAttribute("BreakdownServiceNo", "N.A.");
            }
            if (!objOD.isNull("DistributorServices")) {
                row.setAttribute("Services", String.valueOf(objOD.get("DistributorServices")));
            }else{
                row.setAttribute("Services", "N.A.");
            }
            if (!objOD.isNull("Email")) {
                row.setAttribute("Email", String.valueOf(objOD.get("Email")));
            }else{
                row.setAttribute("Email", "N.A.");
            }
            if (!objOD.isNull("Telephone")) {
                row.setAttribute("Telephone", String.valueOf(objOD.get("Telephone")));
            }else{
                row.setAttribute("Telephone", "N.A.");
            }
            if (!objOD.isNull("DistributorCode")) {
                row.setAttribute("PartnerCode", String.valueOf(objOD.get("DistributorCode")));
            }else{
                row.setAttribute("PartnerCode", "N.A.");
            }
            if (!objOD.isNull("DistributorName")) {
                row.setAttribute("PartnerName", String.valueOf(objOD.get("DistributorName")));
            }else{
                row.setAttribute("PartnerName", "N.A.");
            }
            if (!objOD.isNull("DistributorShortName")) {
                row.setAttribute("PartnerShortName", String.valueOf(objOD.get("DistributorShortName")));
            }else{
                row.setAttribute("PartnerShortName", "N.A.");
            }
            if (!objOD.isNull("TelF1")) {
                row.setAttribute("TelF1", String.valueOf(objOD.get("TelF1")));
            }else{
                row.setAttribute("TelF1", "N.A.");
            }
            
            if (!objOD.isNull("Pin")) {
                row.setAttribute(EPICConstant.PIN, objOD.getString("Pin"));
            }else{
                row.setAttribute(EPICConstant.PIN, "N.A.");
            }
            if (!objOD.isNull("Latitude")) {
                row.setAttribute("Latitude", String.valueOf(objOD.get("Latitude")));
            }else{
                row.setAttribute("Latitude", "N.A.");
            }
            if (!objOD.isNull("SalesOrgName")) {
                row.setAttribute("SalesOrgName", String.valueOf(objOD.get("SalesOrgName")));
            }else{
                row.setAttribute("SalesOrgName", "N.A.");
            }
            if (!objOD.isNull("Longitude")) {
                row.setAttribute("Longitude", String.valueOf(objOD.get("Longitude")));
            }else{
                row.setAttribute("Longitude", "N.A.");
            }
            if (!objOD.isNull("CustStateName")) {
                row.setAttribute(EPICConstant.CUSTSTATENAME, String.valueOf(objOD.get("CustStateName")));
            }else{
                row.setAttribute(EPICConstant.CUSTSTATENAME, "N.A.");
            }
            if (!objOD.isNull("DistrictName")) {
                row.setAttribute(EPICConstant.DISTRICTNAME, String.valueOf(objOD.get("DistrictName")));
            }else{
                row.setAttribute(EPICConstant.DISTRICTNAME, "N.A.");
            }
            if (!objOD.isNull("SalesOffName")) {
                row.setAttribute("SalesOffName", String.valueOf(objOD.get("SalesOffName")));
            }else{
                row.setAttribute("SalesOffName", "N.A.");
            }
            if (!objOD.isNull("WorkTimingStart")) {
                row.setAttribute("WorkTimingStart", String.valueOf(objOD.get("WorkTimingStart")));
            }else{
                row.setAttribute("WorkTimingStart", "N.A.");
            }
            if (!objOD.isNull("Promo")) {
                row.setAttribute("Promo", String.valueOf(objOD.get("Promo")));
            }else{
                row.setAttribute("Promo", "N.A.");
            }
            if (!objOD.isNull("Distributoraddress")) {
                row.setAttribute("Address", String.valueOf(objOD.get("Distributoraddress")));
            }else{
                row.setAttribute("Address", "N.A.");
            }
            if (!objOD.isNull("State")) {
                row.setAttribute("State", String.valueOf(objOD.get("State")));
            }else{
                row.setAttribute("State", "N.A.");
            }
            if (!objOD.isNull("WorkTimingEnd")) {
                row.setAttribute("WorkTimingEnd", String.valueOf(objOD.get("WorkTimingEnd")));
            }else{
                row.setAttribute("WorkTimingEnd", "N.A.");
            }                  
            this.insertRow(row);
        }
        
    }
    
    
    
    /*
     * Below Method is Used for EPICConstant.CHECK_APPLICATION_STATUS Case 
     * in serviceLPGCall method
     * */
    public void populatePartnerStockist(String jsonInpString) {
        System.out.println("jsonInpString "+jsonInpString);
        JSONObject jsonObject = new JSONObject(jsonInpString);
        JSONObject jsonResponse = jsonObject.getJSONObject("MapObject");
        JSONArray arrObj =jsonResponse.getJSONArray("VwMobLUBESInfo");
        log.info("arrObj "+arrObj);
        this.getViewObject().executeEmptyRowSet();
        for (int i = 0; i < arrObj.length(); i++) {
            JSONObject objOD = arrObj.getJSONObject(i);
            Row row = this.createRow();
            if (!objOD.isNull("SalesAreaName")) {
                row.setAttribute("SalesAreaName", String.valueOf(objOD.get("SalesAreaName")));
            }else{
                row.setAttribute("SalesAreaName", "N.A.");
            }
            if (!objOD.isNull("BreakdownServiceNo")) {
                row.setAttribute("BreakdownServiceNo", String.valueOf(objOD.get("BreakdownServiceNo")));
            }else{
                row.setAttribute("BreakdownServiceNo", "N.A.");
            }
            if (!objOD.isNull("StockistServices")) {
                row.setAttribute("Services", String.valueOf(objOD.get("StockistServices")));
            }else{
                row.setAttribute("Services", "N.A.");
            }
            if (!objOD.isNull("Email")) {
                row.setAttribute("Email", String.valueOf(objOD.get("Email")));
            }else{
                row.setAttribute("Email", "N.A.");
            }
            if (!objOD.isNull("Telephone")) {
                row.setAttribute("Telephone", String.valueOf(objOD.get("Telephone")));
            }else{
                row.setAttribute("Telephone", "N.A.");
            }
            if (!objOD.isNull("StockistCode")) {
                row.setAttribute("PartnerCode", String.valueOf(objOD.get("StockistCode")));
            }else{
                row.setAttribute("PartnerCode", "N.A.");
            }
            if (!objOD.isNull("StockistName")) {
                row.setAttribute("PartnerName", String.valueOf(objOD.get("StockistName")));
            }else{
                row.setAttribute("PartnerName", "N.A.");
            }
            if (!objOD.isNull("StockistShortName")) {
                row.setAttribute("PartnerShortName", String.valueOf(objOD.get("StockistShortName")));
            }else{
                row.setAttribute("PartnerShortName", "N.A.");
            }
            if (!objOD.isNull("TelF1")) {
                row.setAttribute("TelF1", String.valueOf(objOD.get("TelF1")));
            }else{
                row.setAttribute("TelF1", "N.A.");
            }
            
            if (!objOD.isNull("Pin")) {
                row.setAttribute(EPICConstant.PIN, objOD.getString("Pin"));
            }else{
                row.setAttribute(EPICConstant.PIN, "N.A.");
            }
            if (!objOD.isNull("Latitude")) {
                row.setAttribute("Latitude", String.valueOf(objOD.get("Latitude")));
            }else{
                row.setAttribute("Latitude", "N.A.");
            }
            if (!objOD.isNull("SalesOrgName")) {
                row.setAttribute("SalesOrgName", String.valueOf(objOD.get("SalesOrgName")));
            }else{
                row.setAttribute("SalesOrgName", "N.A.");
            }
            if (!objOD.isNull("Longitude")) {
                row.setAttribute("Longitude", String.valueOf(objOD.get("Longitude")));
            }else{
                row.setAttribute("Longitude", "N.A.");
            }
            if (!objOD.isNull("CustStateName")) {
                row.setAttribute(EPICConstant.CUSTSTATENAME, String.valueOf(objOD.get("CustStateName")));
            }else{
                row.setAttribute(EPICConstant.CUSTSTATENAME, "N.A.");
            }
            if (!objOD.isNull("DistrictName")) {
                row.setAttribute(EPICConstant.DISTRICTNAME, String.valueOf(objOD.get("DistrictName")));
            }else{
                row.setAttribute(EPICConstant.DISTRICTNAME, "N.A.");
            }
            if (!objOD.isNull("SalesOffName")) {
                row.setAttribute("SalesOffName", String.valueOf(objOD.get("SalesOffName")));
            }else{
                row.setAttribute("SalesOffName", "N.A.");
            }
            if (!objOD.isNull("WorkTimingStart")) {
                row.setAttribute("WorkTimingStart", String.valueOf(objOD.get("WorkTimingStart")));
            }else{
                row.setAttribute("WorkTimingStart", "N.A.");
            }
            if (!objOD.isNull("Promo")) {
                row.setAttribute("Promo", String.valueOf(objOD.get("Promo")));
            }else{
                row.setAttribute("Promo", "N.A.");
            }
            if (!objOD.isNull("Stockistaddress")) {
                row.setAttribute("Address", String.valueOf(objOD.get("Stockistaddress")));
            }else{
                row.setAttribute("Address", "N.A.");
            }
            if (!objOD.isNull("State")) {
                row.setAttribute("State", String.valueOf(objOD.get("State")));
            }else{
                row.setAttribute("State", "N.A.");
            }
            if (!objOD.isNull("WorkTimingEnd")) {
                row.setAttribute("WorkTimingEnd", String.valueOf(objOD.get("WorkTimingEnd")));
            }else{
                row.setAttribute("WorkTimingEnd", "N.A.");
            }                  
            this.insertRow(row);
        }
        
    }
    
    /*
     * Below Method is Used for EPICConstant.CHECK_APPLICATION_STATUS Case
     * in serviceLPGCall method
     * */
    
    public void insertPDistributorFromJasonArray(JSONArray arrObj) {
        log.info("---------------------insertFromJasonArray Order ----------------------------");
        this.getViewObject().executeEmptyRowSet();
        log.info("arrObj" +arrObj);
        log.info("arrObj.length()" +arrObj.length());

        {
            log.info("logic changed");
    //            for (int i = 0; i < arrObj.length(); i++) {
            for (int i = arrObj.length() - 1; i >= 0; i--) {
                JSONObject objOD = arrObj.getJSONObject(i);
                log.info("Order "+i+" "+arrObj.getJSONObject(i));
                Row row = this.createRow();
                    if (!objOD.isNull("SalesAreaName")) {
                        row.setAttribute("SalesAreaName", String.valueOf(objOD.get("SalesAreaName")));
                    }else{
                        row.setAttribute("SalesAreaName", "N.A.");
                    }
                    if (!objOD.isNull("BreakdownServiceNo")) {
                        row.setAttribute("BreakdownServiceNo", String.valueOf(objOD.get("BreakdownServiceNo")));
                    }else{
                        row.setAttribute("BreakdownServiceNo", "N.A.");
                    }
                    if (!objOD.isNull("DistributorServices")) {
                        row.setAttribute("Services", String.valueOf(objOD.get("DistributorServices")));
                    }else{
                        row.setAttribute("Services", "N.A.");
                    }
                    if (!objOD.isNull("Email")) {
                        row.setAttribute("Email", String.valueOf(objOD.get("Email")));
                    }else{
                        row.setAttribute("Email", "N.A.");
                    }
                    if (!objOD.isNull("Telephone")) {
                        row.setAttribute("Telephone", String.valueOf(objOD.get("Telephone")));
                    }else{
                        row.setAttribute("Telephone", "N.A.");
                    }
                    if (!objOD.isNull("DistributorCode")) {
                        row.setAttribute("PartnerCode", String.valueOf(objOD.get("DistributorCode")));
                    }else{
                        row.setAttribute("PartnerCode", "N.A.");
                    }
                    if (!objOD.isNull("PartnerName")) {
                        row.setAttribute("PartnerName", String.valueOf(objOD.get("PartnerName")));
                    }else{
                        row.setAttribute("PartnerName", "N.A.");
                    }
                    if (!objOD.isNull("DistributorShortName")) {
                        row.setAttribute("PartnerShortName", String.valueOf(objOD.get("DistributorShortName")));
                    }else{
                        row.setAttribute("PartnerShortName", "N.A.");
                    }
                    if (!objOD.isNull("TelF1")) {
                        row.setAttribute("TelF1", String.valueOf(objOD.get("TelF1")));
                    }else{
                        row.setAttribute("TelF1", "N.A.");
                    }
                    
                    if (!objOD.isNull("Pin")) {
                        row.setAttribute(EPICConstant.PIN, objOD.getString("Pin"));
                    }else{
                        row.setAttribute(EPICConstant.PIN, "N.A.");
                    }
                    if (!objOD.isNull("Latitude")) {
                        row.setAttribute("Latitude", String.valueOf(objOD.get("Latitude")));
                    }else{
                        row.setAttribute("Latitude", "N.A.");
                    }
                    if (!objOD.isNull("SalesOrgName")) {
                        row.setAttribute("SalesOrgName", String.valueOf(objOD.get("SalesOrgName")));
                    }else{
                        row.setAttribute("SalesOrgName", "N.A.");
                    }
                    if (!objOD.isNull("Longitude")) {
                        row.setAttribute("Longitude", String.valueOf(objOD.get("Longitude")));
                    }else{
                        row.setAttribute("Longitude", "N.A.");
                    }
                    if (!objOD.isNull("CustStateName")) {
                        row.setAttribute(EPICConstant.CUSTSTATENAME, String.valueOf(objOD.get("CustStateName")));
                    }else{
                        row.setAttribute(EPICConstant.CUSTSTATENAME, "N.A.");
                    }
                    if (!objOD.isNull("DistrictName")) {
                        row.setAttribute(EPICConstant.DISTRICTNAME, String.valueOf(objOD.get("DistrictName")));
                    }else{
                        row.setAttribute(EPICConstant.DISTRICTNAME, "N.A.");
                    }
                    if (!objOD.isNull("SalesOffName")) {
                        row.setAttribute("SalesOffName", String.valueOf(objOD.get("SalesOffName")));
                    }else{
                        row.setAttribute("SalesOffName", "N.A.");
                    }
                    if (!objOD.isNull("WorkTimingStart")) {
                        row.setAttribute("WorkTimingStart", String.valueOf(objOD.get("WorkTimingStart")));
                    }else{
                        row.setAttribute("WorkTimingStart", "N.A.");
                    }
                    if (!objOD.isNull("Promo")) {
                        row.setAttribute("Promo", String.valueOf(objOD.get("Promo")));
                    }else{
                        row.setAttribute("Promo", "N.A.");
                    }
                    if (!objOD.isNull("Address")) {
                        row.setAttribute("Address", String.valueOf(objOD.get("Address")));
                    }else{
                        row.setAttribute("Address", "N.A.");
                    }
                    if (!objOD.isNull("State")) {
                        row.setAttribute("State", String.valueOf(objOD.get("State")));
                    }else{
                        row.setAttribute("State", "N.A.");
                    }
                    if (!objOD.isNull("WorkTimingEnd")) {
                        row.setAttribute("WorkTimingEnd", String.valueOf(objOD.get("WorkTimingEnd")));
                    }else{
                        row.setAttribute("WorkTimingEnd", "N.A.");
                    }                  
                    this.insertRow(row);
            }
            
        }
    }
    
    /*
     * Below Method is Used for EPICConstant.CHECK_APPLICATION_STATUS Case
     * in serviceLPGCall method
     * */
    
    public void insertPStockistFromJasonArray(JSONArray arrObj) {
        log.info("---------------------insertFromJasonArray Order ----------------------------");
        this.getViewObject().executeEmptyRowSet();
        log.info("arrObj" +arrObj);
        log.info("arrObj.length()" +arrObj.length());

        {
            log.info("logic changed");
    //            for (int i = 0; i < arrObj.length(); i++) {
            for (int i = arrObj.length() - 1; i >= 0; i--) {
                JSONObject objOD = arrObj.getJSONObject(i);
                log.info("Order "+i+" "+arrObj.getJSONObject(i));
                Row row = this.createRow();
                if (!objOD.isNull("SalesAreaName")) {
                    row.setAttribute("SalesAreaName", String.valueOf(objOD.get("SalesAreaName")));
                }else{
                    row.setAttribute("SalesAreaName", "N.A.");
                }
                if (!objOD.isNull("BreakdownServiceNo")) {
                    row.setAttribute("BreakdownServiceNo", String.valueOf(objOD.get("BreakdownServiceNo")));
                }else{
                    row.setAttribute("BreakdownServiceNo", "N.A.");
                }
                if (!objOD.isNull("StockistServices")) {
                    row.setAttribute("Services", String.valueOf(objOD.get("StockistServices")));
                }else{
                    row.setAttribute("Services", "N.A.");
                }
                if (!objOD.isNull("Email")) {
                    row.setAttribute("Email", String.valueOf(objOD.get("Email")));
                }else{
                    row.setAttribute("Email", "N.A.");
                }
                if (!objOD.isNull("Telephone")) {
                    row.setAttribute("Telephone", String.valueOf(objOD.get("Telephone")));
                }else{
                    row.setAttribute("Telephone", "N.A.");
                }
                if (!objOD.isNull("StockistCode")) {
                    row.setAttribute("PartnerCode", String.valueOf(objOD.get("StockistCode")));
                }else{
                    row.setAttribute("PartnerCode", "N.A.");
                }
                if (!objOD.isNull("PartnerName")) {
                    row.setAttribute("PartnerName", String.valueOf(objOD.get("PartnerName")));
                }else{
                    row.setAttribute("PartnerName", "N.A.");
                }
                if (!objOD.isNull("StockistShortName")) {
                    row.setAttribute("PartnerShortName", String.valueOf(objOD.get("StockistShortName")));
                }else{
                    row.setAttribute("PartnerShortName", "N.A.");
                }
                if (!objOD.isNull("TelF1")) {
                    row.setAttribute("TelF1", String.valueOf(objOD.get("TelF1")));
                }else{
                    row.setAttribute("TelF1", "N.A.");
                }
                
                if (!objOD.isNull("Pin")) {
                    row.setAttribute(EPICConstant.PIN, objOD.getString("Pin"));
                }else{
                    row.setAttribute(EPICConstant.PIN, "N.A.");
                }
                if (!objOD.isNull("Latitude")) {
                    row.setAttribute("Latitude", String.valueOf(objOD.get("Latitude")));
                }else{
                    row.setAttribute("Latitude", "N.A.");
                }
                if (!objOD.isNull("SalesOrgName")) {
                    row.setAttribute("SalesOrgName", String.valueOf(objOD.get("SalesOrgName")));
                }else{
                    row.setAttribute("SalesOrgName", "N.A.");
                }
                if (!objOD.isNull("Longitude")) {
                    row.setAttribute("Longitude", String.valueOf(objOD.get("Longitude")));
                }else{
                    row.setAttribute("Longitude", "N.A.");
                }
                if (!objOD.isNull("CustStateName")) {
                    row.setAttribute(EPICConstant.CUSTSTATENAME, String.valueOf(objOD.get("CustStateName")));
                }else{
                    row.setAttribute(EPICConstant.CUSTSTATENAME, "N.A.");
                }
                if (!objOD.isNull("DistrictName")) {
                    row.setAttribute(EPICConstant.DISTRICTNAME, String.valueOf(objOD.get("DistrictName")));
                }else{
                    row.setAttribute(EPICConstant.DISTRICTNAME, "N.A.");
                }
                if (!objOD.isNull("SalesOffName")) {
                    row.setAttribute("SalesOffName", String.valueOf(objOD.get("SalesOffName")));
                }else{
                    row.setAttribute("SalesOffName", "N.A.");
                }
                if (!objOD.isNull("WorkTimingStart")) {
                    row.setAttribute("WorkTimingStart", String.valueOf(objOD.get("WorkTimingStart")));
                }else{
                    row.setAttribute("WorkTimingStart", "N.A.");
                }
                if (!objOD.isNull("Promo")) {
                    row.setAttribute("Promo", String.valueOf(objOD.get("Promo")));
                }else{
                    row.setAttribute("Promo", "N.A.");
                }
                if (!objOD.isNull("Address")) {
                    row.setAttribute("Address", String.valueOf(objOD.get("Address")));
                }else{
                    row.setAttribute("Address", "N.A.");
                }
                if (!objOD.isNull("State")) {
                    row.setAttribute("State", String.valueOf(objOD.get("State")));
                }else{
                    row.setAttribute("State", "N.A.");
                }
                if (!objOD.isNull("WorkTimingEnd")) {
                    row.setAttribute("WorkTimingEnd", String.valueOf(objOD.get("WorkTimingEnd")));
                }else{
                    row.setAttribute("WorkTimingEnd", "N.A.");
                }                  
                this.insertRow(row);
            }
            
        }
    }
    
}

