package com.iocl.customer.model.viewobject;

import com.iocl.customer.model.utils.EPICConstant;
import com.iocl.customer.model.utils.EPICIOCLResourceModel;
import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;

import org.apache.log4j.Logger;

import ioclcommonproj.com.iocl.utils.JSONArray;
import ioclcommonproj.com.iocl.utils.JSONObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 28 15:25:51 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ROLocatorVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ROLocatorVOImpl() {
        String logFlag = EPICIOCLResourceModel.findKeyValue("LOGS_PRINT_FLAG");
        if (logFlag != null && "Y".equalsIgnoreCase(logFlag)) {

            log = Logger.getLogger(ROLocatorVOImpl.class);

        } else {
            log = Logger.getLogger(ROLocatorVOImpl.class);
            Logger.getRootLogger().setLevel(org.apache.log4j.Level.OFF);
        }
    }
    
    private static Logger log ;
    
    /*
     * Below Method is Used for EPICConstant.CHECK_APPLICATION_STATUS Case 
     * in serviceLPGCall method
     * */
    public void populateROData(String jsonInpString) {
        System.out.println("jsonInpString "+jsonInpString);
        JSONObject jsonObject = new JSONObject(jsonInpString);
        JSONObject jsonResponse = jsonObject.getJSONObject("VwMobRoinfoCollection");
        JSONArray arrObj =jsonResponse.getJSONArray("VwMobRoinfo");
        log.info("arrObj "+arrObj);
        this.getViewObject().executeEmptyRowSet();
        for (int i = 0; i < arrObj.length(); i++) {
            JSONObject objOD = arrObj.getJSONObject(i);
            Row row = this.createRow();
            if (!objOD.isNull("ROCode")) {
                row.setAttribute(EPICConstant.ROCODE, objOD.getString("ROCode"));
            }else{
                row.setAttribute(EPICConstant.ROCODE, "N.A.");
            }
            if (!objOD.isNull("ROName")) {
                row.setAttribute(EPICConstant.RONAME, objOD.getString("ROName"));
            }else{
                row.setAttribute(EPICConstant.RONAME, "N.A.");
            }
            if (!objOD.isNull("ROaddress")) {
                row.setAttribute(EPICConstant.ROADDRESS, objOD.getString("ROaddress"));
            }else{
                row.setAttribute(EPICConstant.ROADDRESS, "N.A.");
            }
            if (!objOD.isNull("Pin")) {
                row.setAttribute(EPICConstant.PIN, objOD.getString("Pin"));
            }else{
                row.setAttribute(EPICConstant.PIN, "N.A.");
            }
            if (!objOD.isNull("State")) {
                row.setAttribute(EPICConstant.STATE, objOD.getString("State"));
            }else{
                row.setAttribute(EPICConstant.STATE, "N.A.");
            }
            if (!objOD.isNull("DoCode")) {
                row.setAttribute(EPICConstant.DOCODE, objOD.getString("DoCode"));
            }else{
                row.setAttribute(EPICConstant.DOCODE, "N.A.");
            }
            if (!objOD.isNull("SOCode")) {
                row.setAttribute(EPICConstant.SOCODE, objOD.getString("SOCode"));
            }else{
                row.setAttribute(EPICConstant.SOCODE, "N.A.");
            }
            if (!objOD.isNull("Telephone")) {
                row.setAttribute(EPICConstant.TELEPHONE, objOD.getString("Telephone"));
            }else{
                row.setAttribute(EPICConstant.TELEPHONE, "N.A.");
            }
            if (!objOD.isNull("Latitude")) {
                row.setAttribute(EPICConstant.LATITUDE_VO, objOD.getString("Latitude"));
            }else{
                row.setAttribute(EPICConstant.LATITUDE_VO, "N.A.");
            }
            if (!objOD.isNull("Longitude")) {
                row.setAttribute(EPICConstant.LONGITUDE_VO, objOD.getString("Longitude"));
            }else{
                row.setAttribute(EPICConstant.LONGITUDE_VO, "N.A.");
            }
            if (!objOD.isNull("DealerName")) {
                row.setAttribute(EPICConstant.DEALERNAME, objOD.getString("DealerName"));
            }else{
                row.setAttribute(EPICConstant.DEALERNAME, "N.A.");
            }
            if (!objOD.isNull("WorkTimingStart")) {
                row.setAttribute(EPICConstant.WORKTIMIMGSTART, objOD.getString("WorkTimingStart"));
            }else{
                row.setAttribute(EPICConstant.WORKTIMIMGSTART, "N.A.");
            }
            if (!objOD.isNull("WorkTimingEnd")) {
                row.setAttribute(EPICConstant.WORKTIMIMGEND, objOD.getString("WorkTimingEnd"));
            }else{
                row.setAttribute(EPICConstant.WORKTIMIMGEND, "N.A.");
            }
            if (!objOD.isNull("MS")) {
                row.setAttribute(EPICConstant.MS, objOD.getString("MS"));
            }else{
                row.setAttribute(EPICConstant.MS, "N.A.");
            }
            if (!objOD.isNull("HSD")) {
                row.setAttribute(EPICConstant.HSD, objOD.getString("HSD"));
            }else{
                row.setAttribute(EPICConstant.HSD, "N.A.");
            }
            if (!objOD.isNull("XP")) {
                row.setAttribute(EPICConstant.XP, objOD.getString("XP"));
            }else{
                row.setAttribute(EPICConstant.XP, "N.A.");
            }
            if (!objOD.isNull("XM")) {
                row.setAttribute(EPICConstant.XM, objOD.getString("XM"));
            }else{
                row.setAttribute(EPICConstant.XM, "N.A.");
            }
            if (!objOD.isNull("TelF1")) {
                row.setAttribute(EPICConstant.TELF1, objOD.getString("TelF1"));
            }else{
                row.setAttribute(EPICConstant.TELF1, "N.A.");
            }
            if (!objOD.isNull("SalesOrgName")) {
                row.setAttribute(EPICConstant.SALESORGNAME, objOD.getString("SalesOrgName"));
            }else{
                row.setAttribute(EPICConstant.SALESORGNAME, "N.A.");
            }
            if (!objOD.isNull("SalesOffName")) {
                row.setAttribute(EPICConstant.SALESOFFICENAME, objOD.getString("SalesOffName"));
            }else{
                row.setAttribute(EPICConstant.SALESOFFICENAME, "N.A.");
            }
            if (!objOD.isNull("SalesAreaName")) {
                row.setAttribute(EPICConstant.SALESAREANAME,objOD.getString("SalesAreaName"));
            }else{
                row.setAttribute(EPICConstant.SALESAREANAME, "N.A.");
            }
            if (!objOD.isNull("DistrictName")) {
                row.setAttribute(EPICConstant.DISTRICTNAME, objOD.getString("DistrictName"));
            }else{
                row.setAttribute(EPICConstant.DISTRICTNAME, "N.A.");
            }
            if (!objOD.isNull("CustStateName")) {
                row.setAttribute(EPICConstant.CUSTSTATENAME, objOD.getString("CustStateName"));
            }else{
                row.setAttribute(EPICConstant.CUSTSTATENAME, "N.A.");
            }
            if (!objOD.isNull("ROMktType")) {
                row.setAttribute(EPICConstant.ROMKTTYPE, objOD.getString("ROMktType"));
            }else{
                row.setAttribute(EPICConstant.ROMKTTYPE, "N.A.");
            }
            if (!objOD.isNull("Email")) {
                row.setAttribute(EPICConstant.EMAIL, objOD.getString("Email"));
            }else{
                row.setAttribute(EPICConstant.EMAIL, "N.A.");
            }
            if (!objOD.isNull("ROServices")) {
                String str=objOD.getString("ROServices").toString().replaceAll(",", ", ");
                row.setAttribute(EPICConstant.ROSERVICES, str);
            }else{
                row.setAttribute(EPICConstant.ROSERVICES, "N.A.");
            }
            if (!objOD.isNull("ArcheType")) {
                row.setAttribute(EPICConstant.ARCHERTYPE, objOD.getString("ArcheType"));
            }else{
                row.setAttribute(EPICConstant.ARCHERTYPE, "N.A.");
            }            
            this.insertRow(row);
        }
        
    }
    
    /*
     * Below Method is Used for EPICConstant.CHECK_APPLICATION_STATUS Case
     * in serviceLPGCall method
     * */
    
    public void insertFromJasonArray(JSONArray arrObj) {
        log.info("---------------------insertFromJasonArray Order ----------------------------");
        this.getViewObject().executeEmptyRowSet();
        log.info("arrObj" +arrObj);
        log.info("arrObj.length()" +arrObj.length());

        {
            log.info("logic changed");
//            for (int i = 0; i < arrObj.length(); i++) {
            for (int i = arrObj.length() - 1; i >= 0; i--) {
                JSONObject objOD = arrObj.getJSONObject(i);
                log.info("Order "+i+" "+arrObj.getJSONObject(i));
                Row row = this.createRow();
                if (!objOD.isNull("ROCode")) {
                    row.setAttribute("ROCode", objOD.getString("ROCode"));
                } else {
                    row.setAttribute("ROCode", "N.A.");
                }
                if (!objOD.isNull("ROName")) {
                    row.setAttribute("ROName", objOD.getString("ROName"));
                    log.info("ROName " + objOD.getString("ROName"));
                } else {
                    row.setAttribute("ROName", "N.A.");
                }
                if (!objOD.isNull("ROaddress")) {
                    row.setAttribute("ROaddress", objOD.getString("ROaddress"));
                } else {
                    row.setAttribute("ROaddress", "N.A.");
                }
                if (!objOD.isNull("Pin")) {
                    row.setAttribute("Pin", objOD.getString("Pin"));
                } else {
                    row.setAttribute("Pin", "N.A.");
                }
                if (!objOD.isNull("State")) {
                    row.setAttribute("State", objOD.getString("State"));
                } else {
                    row.setAttribute("State", "N.A.");
                }
                if (!objOD.isNull("DoCode")) {
                    row.setAttribute("DoCode", objOD.getString("DoCode"));
                } else {
                    row.setAttribute("DoCode", "N.A.");
                }
                if (!objOD.isNull("SOCode")) {
                    row.setAttribute("SOCode", objOD.getString("SOCode"));
                } else {
                    row.setAttribute("SOCode", "N.A.");
                }
                if (!objOD.isNull("Telephone")) {
                    row.setAttribute("Telephone", objOD.getString("Telephone"));
                } else {
                    row.setAttribute("Telephone", "N.A.");
                }
                if (!objOD.isNull("Latitude")) {
                    row.setAttribute("Latitude", objOD.getString("Latitude"));
                } else {
                    row.setAttribute("Latitude", "N.A.");
                }
                if (!objOD.isNull("Longitude")) {
                    row.setAttribute("Longitude", objOD.getString("Longitude"));
                } else {
                    row.setAttribute("Longitude", "N.A.");
                }
                if (!objOD.isNull("DealerName")) {
                    row.setAttribute("DealerName", objOD.getString("DealerName"));
                } else {
                    row.setAttribute("DealerName", "N.A.");
                }
                if (!objOD.isNull("WorkTimingStart")) {
                    row.setAttribute("WorkTimingStart", objOD.getString("WorkTimingStart"));
                } else {
                    row.setAttribute("WorkTimingStart", "N.A.");
                }
                if (!objOD.isNull("WorkTimingEnd")) {
                    row.setAttribute("WorkTimingEnd", objOD.getString("WorkTimingEnd"));
                } else {
                    row.setAttribute("WorkTimingEnd", "N.A.");
                }
                if (!objOD.isNull("MS")) {
                    row.setAttribute("MS", objOD.getString("MS"));
                } else {
                    row.setAttribute("MS", "N.A.");
                }
                if (!objOD.isNull("HSD")) {
                    row.setAttribute("HSD", objOD.getString("HSD"));
                } else {
                    row.setAttribute("HSD", "N.A.");
                }
                if (!objOD.isNull("XP")) {
                    row.setAttribute("XP", objOD.getString("XP"));
                } else {
                    row.setAttribute("XP", "N.A.");
                }
                if (!objOD.isNull("XM")) {
                    row.setAttribute("XM", objOD.getString("XM"));
                } else {
                    row.setAttribute("XM", "N.A.");
                }
                if (!objOD.isNull("TelF1")) {
                    row.setAttribute("TelF1", objOD.getString("TelF1"));
                } else {
                    row.setAttribute("TelF1", "N.A.");
                }
                if (!objOD.isNull("SalesOrgName")) {
                    row.setAttribute("SalesOrgName", objOD.getString("SalesOrgName"));
                } else {
                    row.setAttribute("SalesOrgName", "N.A.");
                }
                if (!objOD.isNull("SalesOffName")) {
                    row.setAttribute("SalesOffName", objOD.getString("SalesOffName"));
                } else {
                    row.setAttribute("SalesOffName", "N.A.");
                }
                if (!objOD.isNull("SalesAreaName")) {
                    row.setAttribute("SalesAreaName", objOD.getString("SalesAreaName"));
                } else {
                    row.setAttribute("SalesAreaName", "N.A.");
                }
                if (!objOD.isNull("DistrictName")) {
                    row.setAttribute("DistrictName", objOD.getString("DistrictName"));
                } else {
                    row.setAttribute("DistrictName", "N.A.");
                }
                if (!objOD.isNull("CustStateName")) {
                    row.setAttribute("CustStateName", objOD.getString("CustStateName"));
                } else {
                    row.setAttribute("CustStateName", "N.A.");
                }
                if (!objOD.isNull("ROMktType")) {
                    row.setAttribute("ROMktType", objOD.getString("ROMktType"));
                } else {
                    row.setAttribute("ROMktType", "N.A.");
                }
                if (!objOD.isNull("Email")) {
                    row.setAttribute("Email", objOD.getString("Email"));
                } else {
                    row.setAttribute("Email", "N.A.");
                }
                if (!objOD.isNull("ROServices")) {
                    String str = objOD.getString("ROServices")
                                      .toString()
                                      .replaceAll(",", ", ");
                    row.setAttribute("ROServices", str);
                } else {
                    row.setAttribute("ROServices", "N.A.");
                }
                if (!objOD.isNull("ArcheType")) {
                    row.setAttribute("ArcheType", objOD.getString("ArcheType"));
                } else {
                    row.setAttribute("ArcheType", "N.A.");
                }
                this.insertRow(row);
            }
            
        }
    }
}

