package com.iocl.customer.model.viewobject;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 28 15:25:45 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ROLocatorVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Dummy,
        ROCode,
        ROName,
        ROaddress,
        Pin,
        State,
        DoCode,
        SOCode,
        Telephone,
        Latitude,
        Longitude,
        DealerName,
        WorkTimingStart,
        WorkTimingEnd,
        MS,
        HSD,
        XP,
        TelF1,
        SalesOrgName,
        SalesOffName,
        SalesAreaName,
        DistrictName,
        CustStateName,
        Email,
        ROMktType,
        ROServices,
        DhruvaFlag,
        ArcheType,
        SalesOrg,
        SalesOff,
        SalesArea,
        XM,
        FireBrigadeContNo,
        PoliceContactNo,
        AmbulaneContNo,
        BreakdownServiceNo,
        HighwayType,
        HighwayNo,
        Promo;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DUMMY = AttributesEnum.Dummy.index();
    public static final int ROCODE = AttributesEnum.ROCode.index();
    public static final int RONAME = AttributesEnum.ROName.index();
    public static final int ROADDRESS = AttributesEnum.ROaddress.index();
    public static final int PIN = AttributesEnum.Pin.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int DOCODE = AttributesEnum.DoCode.index();
    public static final int SOCODE = AttributesEnum.SOCode.index();
    public static final int TELEPHONE = AttributesEnum.Telephone.index();
    public static final int LATITUDE = AttributesEnum.Latitude.index();
    public static final int LONGITUDE = AttributesEnum.Longitude.index();
    public static final int DEALERNAME = AttributesEnum.DealerName.index();
    public static final int WORKTIMINGSTART = AttributesEnum.WorkTimingStart.index();
    public static final int WORKTIMINGEND = AttributesEnum.WorkTimingEnd.index();
    public static final int MS = AttributesEnum.MS.index();
    public static final int HSD = AttributesEnum.HSD.index();
    public static final int XP = AttributesEnum.XP.index();
    public static final int TELF1 = AttributesEnum.TelF1.index();
    public static final int SALESORGNAME = AttributesEnum.SalesOrgName.index();
    public static final int SALESOFFNAME = AttributesEnum.SalesOffName.index();
    public static final int SALESAREANAME = AttributesEnum.SalesAreaName.index();
    public static final int DISTRICTNAME = AttributesEnum.DistrictName.index();
    public static final int CUSTSTATENAME = AttributesEnum.CustStateName.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int ROMKTTYPE = AttributesEnum.ROMktType.index();
    public static final int ROSERVICES = AttributesEnum.ROServices.index();
    public static final int DHRUVAFLAG = AttributesEnum.DhruvaFlag.index();
    public static final int ARCHETYPE = AttributesEnum.ArcheType.index();
    public static final int SALESORG = AttributesEnum.SalesOrg.index();
    public static final int SALESOFF = AttributesEnum.SalesOff.index();
    public static final int SALESAREA = AttributesEnum.SalesArea.index();
    public static final int XM = AttributesEnum.XM.index();
    public static final int FIREBRIGADECONTNO = AttributesEnum.FireBrigadeContNo.index();
    public static final int POLICECONTACTNO = AttributesEnum.PoliceContactNo.index();
    public static final int AMBULANECONTNO = AttributesEnum.AmbulaneContNo.index();
    public static final int BREAKDOWNSERVICENO = AttributesEnum.BreakdownServiceNo.index();
    public static final int HIGHWAYTYPE = AttributesEnum.HighwayType.index();
    public static final int HIGHWAYNO = AttributesEnum.HighwayNo.index();
    public static final int PROMO = AttributesEnum.Promo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ROLocatorVORowImpl() {
    }
}

