package com.iocl.customer.model.viewobject;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 28 12:21:56 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class YesNo_StaticVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public YesNo_StaticVoImpl() {
    }
}

