package com.iocl.customer.model.viewobject.ioclcommonconfig;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 21 14:50:49 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IoclCommonConfigVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public IoclCommonConfigVOImpl() {
    }
}

