package com.iocl.customer.model.viewobject.logssave;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 22 14:39:37 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ServiceLogsSaveVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ServiceLogsSaveVOImpl() {
    }
}

