package com.iocl.customer.model.viewobject.logssave;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 22 14:39:36 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ServiceLogsSaveVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        SvcShortUrl,
        IsSaveLogs,
        Application,
        Comments;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int SVCSHORTURL = AttributesEnum.SvcShortUrl.index();
    public static final int ISSAVELOGS = AttributesEnum.IsSaveLogs.index();
    public static final int APPLICATION = AttributesEnum.Application.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ServiceLogsSaveVORowImpl() {
    }
}

