package com.iocl.customer.model.viewobject.Loyalty.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 10 11:32:17 IST 2018
// ---------------------------------------------------------------------
public interface XtraRCustomerDetailsVORow extends Row {
    String getDummy();

    String getMobileNumber();

    void setMobileNumber(String value);

    String getCardNumber();

    void setCardNumber(String value);

    String getResponseDateTime();

    void setResponseDateTime(String value);

    String getFirstName();

    void setFirstName(String value);

    String getMiddleName();

    void setMiddleName(String value);

    String getLastName();

    void setLastName(String value);

    String getMotherMaidenname();

    void setMotherMaidenname(String value);

    String getOfficePhn();

    void setOfficePhn(String value);

    String getAadharNo();

    void setAadharNo(String value);

    String getEmail();

    void setEmail(String value);

    String getStateName();

    void setStateName(String value);

    String getCityname();

    void setCityname(String value);

    String getAddress1();

    void setAddress1(String value);

    String getAddress2();

    void setAddress2(String value);

    String getAddress3();

    void setAddress3(String value);

    String getAddress4();

    void setAddress4(String value);

    String getPincode();

    void setPincode(String value);

    String getGender();

    void setGender(String value);

    String getResidencePhone();

    void setResidencePhone(String value);

    String getDistrictName();

    void setDistrictName(String value);

    String getAnnualIncome();

    void setAnnualIncome(String value);

    String getDOB();

    void setDOB(String value);

    String getBalancePoints();

    void setBalancePoints(String value);
}

