package com.iocl.customer.model.viewobject.Loyalty;

import com.iocl.customer.model.utils.EPICConstant;

import com.iocl.customer.model.utils.EPICIOCLResourceModel;

import com.iocl.customer.model.utils.ModelUtils;

import ioclcommonproj.com.iocl.utils.JSONObject;

import java.text.DateFormat;
import java.text.SimpleDateFormat;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;

import org.apache.log4j.Logger;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 06 12:07:31 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EnrollmentDbVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EnrollmentDbVoImpl() {
        String logFlag = EPICIOCLResourceModel.findKeyValue("LOGS_PRINT_FLAG");
        if (logFlag != null && "Y".equalsIgnoreCase(logFlag)) {

            log = Logger.getLogger(EnrollmentDbVoImpl.class);

        } else {
            log = Logger.getLogger(EnrollmentDbVoImpl.class);
            Logger.getRootLogger().setLevel(org.apache.log4j.Level.OFF);
        }
    }
    
    private static Logger log ;
    
    public String setProfileEnrichment(String jsonString) {
        log.info("Inside setProfileEnrichment");
        if (jsonString != null) {
            JSONObject jsonInput = new JSONObject(jsonString);
            Row currentRow = this.getCurrentRow();
            
            /*-------Code to Change date format to dd-mm-yyyy----*/
            String dobInString = null;
            if (currentRow.getAttribute(EPICConstant.DATE_OF_BIRTH) != null) {
                Date dob =
                    ModelUtils.dateCompToJBODate(currentRow.getAttribute(EPICConstant.DATE_OF_BIRTH).toString(), String.valueOf(4));
                DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                if (dob != null) {
                    dobInString = formatter.format(dob.dateValue());
                    log.info("dobInString" + dobInString);
                }
            }
            /*----------------End Here---------------*/
            
            jsonInput.put("Prefix", currentRow.getAttribute("Prefix"));
            jsonInput.put(EPICConstant.FIRST_NAME, currentRow.getAttribute(EPICConstant.FIRST_NAME));
            jsonInput.put(EPICConstant.MIDDLE_NAME, currentRow.getAttribute(EPICConstant.MIDDLE_NAME));
            jsonInput.put(EPICConstant.LAST_NAME, currentRow.getAttribute(EPICConstant.LAST_NAME));
            jsonInput.put("Gender", currentRow.getAttribute("Gender"));
            jsonInput.put(EPICConstant.DATE_OF_BIRTH,dobInString);
            jsonInput.put("MotherMaidenName", currentRow.getAttribute("MotherMaidenName"));
            jsonInput.put(EPICConstant.ADDRESS1, currentRow.getAttribute(EPICConstant.ADDRESS1));
            jsonInput.put(EPICConstant.ADDRESS2, currentRow.getAttribute(EPICConstant.ADDRESS2));
            jsonInput.put(EPICConstant.ADDRESS3, currentRow.getAttribute(EPICConstant.ADDRESS3));
            jsonInput.put("Address4", currentRow.getAttribute("Address4"));
            jsonInput.put(EPICConstant.STATE, currentRow.getAttribute(EPICConstant.STATE));
            jsonInput.put(EPICConstant.DISTRICT, currentRow.getAttribute(EPICConstant.DISTRICT));
            jsonInput.put(EPICConstant.CITY, currentRow.getAttribute(EPICConstant.CITY));
            jsonInput.put(EPICConstant.PINCODE, currentRow.getAttribute(EPICConstant.PINCODE));
            
            String officePhoneNoVar = (currentRow.getAttribute("OfficePhoneStd") == null ? "" :currentRow.getAttribute("OfficePhoneStd").toString())+ (currentRow.getAttribute("OfficePhoneNo") == null ? "":currentRow.getAttribute("OfficePhoneNo").toString());
            jsonInput.put("OfficePhoneNo",officePhoneNoVar);
            String residencePhoneNoVar = (currentRow.getAttribute("ResidencePhoneStd") == null ? "" :currentRow.getAttribute("ResidencePhoneStd").toString())+ (currentRow.getAttribute("ResidencePhoneNo") == null ? "":currentRow.getAttribute("ResidencePhoneNo").toString());
            jsonInput.put("ResidencePhoneNo",residencePhoneNoVar);
            
            jsonInput.put("EmailId", currentRow.getAttribute("EmailId"));
            jsonInput.put(EPICConstant.MOBILE_NO, currentRow.getAttribute(EPICConstant.MOBILE_NO));
            jsonInput.put("AnnualIncome", currentRow.getAttribute("AnnualIncome"));
            jsonInput.put("AadharNumber",ModelUtils.evaluateEL("#{sessionScope.sLoyaltyAadharNumber}"));
//            jsonInput.put("AadharNumber", currentRow.getAttribute("AadharNumber"));
            return jsonInput.toString();
        } else
            return null;
    }
    
}

