package com.iocl.customer.model.viewobject.Loyalty;

import com.iocl.customer.model.viewobject.Loyalty.common.XtraRCustomerDetailsVORow;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 10 11:32:12 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XtraRCustomerDetailsVORowImpl extends ViewRowImpl implements XtraRCustomerDetailsVORow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Dummy,
        MobileNumber,
        CardNumber,
        ResponseDateTime,
        FirstName,
        MiddleName,
        LastName,
        MotherMaidenname,
        OfficePhn,
        AadharNo,
        Email,
        StateName,
        Cityname,
        Address1,
        Address2,
        Address3,
        Address4,
        Pincode,
        Gender,
        ResidencePhone,
        DistrictName,
        AnnualIncome,
        DOB,
        BalancePoints,
        Title;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return XtraRCustomerDetailsVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return XtraRCustomerDetailsVORowImpl.AttributesEnum.firstIndex() + XtraRCustomerDetailsVORowImpl.AttributesEnum
                                                                                                            .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = XtraRCustomerDetailsVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DUMMY = AttributesEnum.Dummy.index();
    public static final int MOBILENUMBER = AttributesEnum.MobileNumber.index();
    public static final int CARDNUMBER = AttributesEnum.CardNumber.index();
    public static final int RESPONSEDATETIME = AttributesEnum.ResponseDateTime.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int MIDDLENAME = AttributesEnum.MiddleName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int MOTHERMAIDENNAME = AttributesEnum.MotherMaidenname.index();
    public static final int OFFICEPHN = AttributesEnum.OfficePhn.index();
    public static final int AADHARNO = AttributesEnum.AadharNo.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int STATENAME = AttributesEnum.StateName.index();
    public static final int CITYNAME = AttributesEnum.Cityname.index();
    public static final int ADDRESS1 = AttributesEnum.Address1.index();
    public static final int ADDRESS2 = AttributesEnum.Address2.index();
    public static final int ADDRESS3 = AttributesEnum.Address3.index();
    public static final int ADDRESS4 = AttributesEnum.Address4.index();
    public static final int PINCODE = AttributesEnum.Pincode.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int RESIDENCEPHONE = AttributesEnum.ResidencePhone.index();
    public static final int DISTRICTNAME = AttributesEnum.DistrictName.index();
    public static final int ANNUALINCOME = AttributesEnum.AnnualIncome.index();
    public static final int DOB = AttributesEnum.DOB.index();
    public static final int BALANCEPOINTS = AttributesEnum.BalancePoints.index();
    public static final int TITLE = AttributesEnum.Title.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XtraRCustomerDetailsVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Dummy.
     * @return the Dummy
     */
    public String getDummy() {
        return (String) getAttributeInternal(DUMMY);
    }

    /**
     * Gets the attribute value for the calculated attribute MobileNumber.
     * @return the MobileNumber
     */
    public String getMobileNumber() {
        return (String) getAttributeInternal(MOBILENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MobileNumber.
     * @param value value to set the  MobileNumber
     */
    public void setMobileNumber(String value) {
        setAttributeInternal(MOBILENUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CardNumber.
     * @return the CardNumber
     */
    public String getCardNumber() {
        return (String) getAttributeInternal(CARDNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CardNumber.
     * @param value value to set the  CardNumber
     */
    public void setCardNumber(String value) {
        setAttributeInternal(CARDNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ResponseDateTime.
     * @return the ResponseDateTime
     */
    public String getResponseDateTime() {
        return (String) getAttributeInternal(RESPONSEDATETIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ResponseDateTime.
     * @param value value to set the  ResponseDateTime
     */
    public void setResponseDateTime(String value) {
        setAttributeInternal(RESPONSEDATETIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FirstName.
     * @return the FirstName
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FirstName.
     * @param value value to set the  FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MiddleName.
     * @return the MiddleName
     */
    public String getMiddleName() {
        return (String) getAttributeInternal(MIDDLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MiddleName.
     * @param value value to set the  MiddleName
     */
    public void setMiddleName(String value) {
        setAttributeInternal(MIDDLENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastName.
     * @return the LastName
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastName.
     * @param value value to set the  LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MotherMaidenname.
     * @return the MotherMaidenname
     */
    public String getMotherMaidenname() {
        return (String) getAttributeInternal(MOTHERMAIDENNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MotherMaidenname.
     * @param value value to set the  MotherMaidenname
     */
    public void setMotherMaidenname(String value) {
        setAttributeInternal(MOTHERMAIDENNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OfficePhn.
     * @return the OfficePhn
     */
    public String getOfficePhn() {
        return (String) getAttributeInternal(OFFICEPHN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OfficePhn.
     * @param value value to set the  OfficePhn
     */
    public void setOfficePhn(String value) {
        setAttributeInternal(OFFICEPHN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AadharNo.
     * @return the AadharNo
     */
    public String getAadharNo() {
        return (String) getAttributeInternal(AADHARNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AadharNo.
     * @param value value to set the  AadharNo
     */
    public void setAadharNo(String value) {
        setAttributeInternal(AADHARNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Email.
     * @return the Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Email.
     * @param value value to set the  Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StateName.
     * @return the StateName
     */
    public String getStateName() {
        return (String) getAttributeInternal(STATENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StateName.
     * @param value value to set the  StateName
     */
    public void setStateName(String value) {
        setAttributeInternal(STATENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Cityname.
     * @return the Cityname
     */
    public String getCityname() {
        return (String) getAttributeInternal(CITYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Cityname.
     * @param value value to set the  Cityname
     */
    public void setCityname(String value) {
        setAttributeInternal(CITYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Address1.
     * @return the Address1
     */
    public String getAddress1() {
        return (String) getAttributeInternal(ADDRESS1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Address1.
     * @param value value to set the  Address1
     */
    public void setAddress1(String value) {
        setAttributeInternal(ADDRESS1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Address2.
     * @return the Address2
     */
    public String getAddress2() {
        return (String) getAttributeInternal(ADDRESS2);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Address2.
     * @param value value to set the  Address2
     */
    public void setAddress2(String value) {
        setAttributeInternal(ADDRESS2, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Address3.
     * @return the Address3
     */
    public String getAddress3() {
        return (String) getAttributeInternal(ADDRESS3);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Address3.
     * @param value value to set the  Address3
     */
    public void setAddress3(String value) {
        setAttributeInternal(ADDRESS3, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Address4.
     * @return the Address4
     */
    public String getAddress4() {
        return (String) getAttributeInternal(ADDRESS4);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Address4.
     * @param value value to set the  Address4
     */
    public void setAddress4(String value) {
        setAttributeInternal(ADDRESS4, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Pincode.
     * @return the Pincode
     */
    public String getPincode() {
        return (String) getAttributeInternal(PINCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Pincode.
     * @param value value to set the  Pincode
     */
    public void setPincode(String value) {
        setAttributeInternal(PINCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Gender.
     * @return the Gender
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Gender.
     * @param value value to set the  Gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ResidencePhone.
     * @return the ResidencePhone
     */
    public String getResidencePhone() {
        return (String) getAttributeInternal(RESIDENCEPHONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ResidencePhone.
     * @param value value to set the  ResidencePhone
     */
    public void setResidencePhone(String value) {
        setAttributeInternal(RESIDENCEPHONE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DistrictName.
     * @return the DistrictName
     */
    public String getDistrictName() {
        return (String) getAttributeInternal(DISTRICTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DistrictName.
     * @param value value to set the  DistrictName
     */
    public void setDistrictName(String value) {
        setAttributeInternal(DISTRICTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AnnualIncome.
     * @return the AnnualIncome
     */
    public String getAnnualIncome() {
        return (String) getAttributeInternal(ANNUALINCOME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AnnualIncome.
     * @param value value to set the  AnnualIncome
     */
    public void setAnnualIncome(String value) {
        setAttributeInternal(ANNUALINCOME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DOB.
     * @return the DOB
     */
    public String getDOB() {
        return (String) getAttributeInternal(DOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DOB.
     * @param value value to set the  DOB
     */
    public void setDOB(String value) {
        setAttributeInternal(DOB, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BalancePoints.
     * @return the BalancePoints
     */
    public String getBalancePoints() {
        return (String) getAttributeInternal(BALANCEPOINTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BalancePoints.
     * @param value value to set the  BalancePoints
     */
    public void setBalancePoints(String value) {
        setAttributeInternal(BALANCEPOINTS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Title.
     * @return the Title
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Title.
     * @param value value to set the  Title
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }
}

