package com.iocl.customer.model.viewobject.lpgerrorstrial;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 18 16:30:44 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LpgErrorsTrailEOViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LpgErrorsTrailEOViewImpl() {
    }
}

