package com.iocl.customer.model.viewobject.lpgerrorstrial;

import java.sql.Timestamp;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 18 16:30:42 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LpgErrorsTrailEOViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_LPGERRORSTRAILEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        TrackingId,
        ServiceInput,
        ServiceOutput,
        LpgErrorCode,
        LpgErrorDesc,
        Time,
        ServiceUrl,
        UserSessionTrackingId,
        UserId,
        HeaderAttribute,
        SvcRespTime;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int TRACKINGID = AttributesEnum.TrackingId.index();
    public static final int SERVICEINPUT = AttributesEnum.ServiceInput.index();
    public static final int SERVICEOUTPUT = AttributesEnum.ServiceOutput.index();
    public static final int LPGERRORCODE = AttributesEnum.LpgErrorCode.index();
    public static final int LPGERRORDESC = AttributesEnum.LpgErrorDesc.index();
    public static final int TIME = AttributesEnum.Time.index();
    public static final int SERVICEURL = AttributesEnum.ServiceUrl.index();
    public static final int USERSESSIONTRACKINGID = AttributesEnum.UserSessionTrackingId.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int HEADERATTRIBUTE = AttributesEnum.HeaderAttribute.index();
    public static final int SVCRESPTIME = AttributesEnum.SvcRespTime.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LpgErrorsTrailEOViewRowImpl() {
    }
}

