package com.iocl.customer.model.entityobject;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 06 11:05:07 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LevelDDataEoImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Id,
        Col2,
        Col3,
        Col4,
        Col5,
        Col6,
        Col7,
        Col8,
        Col9,
        Col10,
        Col11,
        Col12,
        Col13,
        Col14,
        Col15,
        Col16,
        Col17,
        Col18,
        Col19,
        Col20,
        Col21,
        Col22,
        Col23,
        Col24,
        Col25,
        Col26,
        Col27,
        Col28,
        Col29,
        Col30,
        Col31,
        Flowcode;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int COL2 = AttributesEnum.Col2.index();
    public static final int COL3 = AttributesEnum.Col3.index();
    public static final int COL4 = AttributesEnum.Col4.index();
    public static final int COL5 = AttributesEnum.Col5.index();
    public static final int COL6 = AttributesEnum.Col6.index();
    public static final int COL7 = AttributesEnum.Col7.index();
    public static final int COL8 = AttributesEnum.Col8.index();
    public static final int COL9 = AttributesEnum.Col9.index();
    public static final int COL10 = AttributesEnum.Col10.index();
    public static final int COL11 = AttributesEnum.Col11.index();
    public static final int COL12 = AttributesEnum.Col12.index();
    public static final int COL13 = AttributesEnum.Col13.index();
    public static final int COL14 = AttributesEnum.Col14.index();
    public static final int COL15 = AttributesEnum.Col15.index();
    public static final int COL16 = AttributesEnum.Col16.index();
    public static final int COL17 = AttributesEnum.Col17.index();
    public static final int COL18 = AttributesEnum.Col18.index();
    public static final int COL19 = AttributesEnum.Col19.index();
    public static final int COL20 = AttributesEnum.Col20.index();
    public static final int COL21 = AttributesEnum.Col21.index();
    public static final int COL22 = AttributesEnum.Col22.index();
    public static final int COL23 = AttributesEnum.Col23.index();
    public static final int COL24 = AttributesEnum.Col24.index();
    public static final int COL25 = AttributesEnum.Col25.index();
    public static final int COL26 = AttributesEnum.Col26.index();
    public static final int COL27 = AttributesEnum.Col27.index();
    public static final int COL28 = AttributesEnum.Col28.index();
    public static final int COL29 = AttributesEnum.Col29.index();
    public static final int COL30 = AttributesEnum.Col30.index();
    public static final int COL31 = AttributesEnum.Col31.index();
    public static final int FLOWCODE = AttributesEnum.Flowcode.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LevelDDataEoImpl() {
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for Col2, using the alias name Col2.
     * @return the value of Col2
     */
    public String getCol2() {
        return (String) getAttributeInternal(COL2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col2.
     * @param value value to set the Col2
     */
    public void setCol2(String value) {
        setAttributeInternal(COL2, value);
    }

    /**
     * Gets the attribute value for Col3, using the alias name Col3.
     * @return the value of Col3
     */
    public String getCol3() {
        return (String) getAttributeInternal(COL3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col3.
     * @param value value to set the Col3
     */
    public void setCol3(String value) {
        setAttributeInternal(COL3, value);
    }

    /**
     * Gets the attribute value for Col4, using the alias name Col4.
     * @return the value of Col4
     */
    public String getCol4() {
        return (String) getAttributeInternal(COL4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col4.
     * @param value value to set the Col4
     */
    public void setCol4(String value) {
        setAttributeInternal(COL4, value);
    }

    /**
     * Gets the attribute value for Col5, using the alias name Col5.
     * @return the value of Col5
     */
    public String getCol5() {
        return (String) getAttributeInternal(COL5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col5.
     * @param value value to set the Col5
     */
    public void setCol5(String value) {
        setAttributeInternal(COL5, value);
    }

    /**
     * Gets the attribute value for Col6, using the alias name Col6.
     * @return the value of Col6
     */
    public String getCol6() {
        return (String) getAttributeInternal(COL6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col6.
     * @param value value to set the Col6
     */
    public void setCol6(String value) {
        setAttributeInternal(COL6, value);
    }

    /**
     * Gets the attribute value for Col7, using the alias name Col7.
     * @return the value of Col7
     */
    public String getCol7() {
        return (String) getAttributeInternal(COL7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col7.
     * @param value value to set the Col7
     */
    public void setCol7(String value) {
        setAttributeInternal(COL7, value);
    }

    /**
     * Gets the attribute value for Col8, using the alias name Col8.
     * @return the value of Col8
     */
    public String getCol8() {
        return (String) getAttributeInternal(COL8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col8.
     * @param value value to set the Col8
     */
    public void setCol8(String value) {
        setAttributeInternal(COL8, value);
    }

    /**
     * Gets the attribute value for Col9, using the alias name Col9.
     * @return the value of Col9
     */
    public String getCol9() {
        return (String) getAttributeInternal(COL9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col9.
     * @param value value to set the Col9
     */
    public void setCol9(String value) {
        setAttributeInternal(COL9, value);
    }

    /**
     * Gets the attribute value for Col10, using the alias name Col10.
     * @return the value of Col10
     */
    public String getCol10() {
        return (String) getAttributeInternal(COL10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col10.
     * @param value value to set the Col10
     */
    public void setCol10(String value) {
        setAttributeInternal(COL10, value);
    }

    /**
     * Gets the attribute value for Col11, using the alias name Col11.
     * @return the value of Col11
     */
    public String getCol11() {
        return (String) getAttributeInternal(COL11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col11.
     * @param value value to set the Col11
     */
    public void setCol11(String value) {
        setAttributeInternal(COL11, value);
    }

    /**
     * Gets the attribute value for Col12, using the alias name Col12.
     * @return the value of Col12
     */
    public String getCol12() {
        return (String) getAttributeInternal(COL12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col12.
     * @param value value to set the Col12
     */
    public void setCol12(String value) {
        setAttributeInternal(COL12, value);
    }

    /**
     * Gets the attribute value for Col13, using the alias name Col13.
     * @return the value of Col13
     */
    public String getCol13() {
        return (String) getAttributeInternal(COL13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col13.
     * @param value value to set the Col13
     */
    public void setCol13(String value) {
        setAttributeInternal(COL13, value);
    }

    /**
     * Gets the attribute value for Col14, using the alias name Col14.
     * @return the value of Col14
     */
    public String getCol14() {
        return (String) getAttributeInternal(COL14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col14.
     * @param value value to set the Col14
     */
    public void setCol14(String value) {
        setAttributeInternal(COL14, value);
    }

    /**
     * Gets the attribute value for Col15, using the alias name Col15.
     * @return the value of Col15
     */
    public String getCol15() {
        return (String) getAttributeInternal(COL15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col15.
     * @param value value to set the Col15
     */
    public void setCol15(String value) {
        setAttributeInternal(COL15, value);
    }

    /**
     * Gets the attribute value for Col16, using the alias name Col16.
     * @return the value of Col16
     */
    public String getCol16() {
        return (String) getAttributeInternal(COL16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col16.
     * @param value value to set the Col16
     */
    public void setCol16(String value) {
        setAttributeInternal(COL16, value);
    }

    /**
     * Gets the attribute value for Col17, using the alias name Col17.
     * @return the value of Col17
     */
    public String getCol17() {
        return (String) getAttributeInternal(COL17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col17.
     * @param value value to set the Col17
     */
    public void setCol17(String value) {
        setAttributeInternal(COL17, value);
    }

    /**
     * Gets the attribute value for Col18, using the alias name Col18.
     * @return the value of Col18
     */
    public String getCol18() {
        return (String) getAttributeInternal(COL18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col18.
     * @param value value to set the Col18
     */
    public void setCol18(String value) {
        setAttributeInternal(COL18, value);
    }

    /**
     * Gets the attribute value for Col19, using the alias name Col19.
     * @return the value of Col19
     */
    public String getCol19() {
        return (String) getAttributeInternal(COL19);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col19.
     * @param value value to set the Col19
     */
    public void setCol19(String value) {
        setAttributeInternal(COL19, value);
    }

    /**
     * Gets the attribute value for Col20, using the alias name Col20.
     * @return the value of Col20
     */
    public String getCol20() {
        return (String) getAttributeInternal(COL20);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col20.
     * @param value value to set the Col20
     */
    public void setCol20(String value) {
        setAttributeInternal(COL20, value);
    }

    /**
     * Gets the attribute value for Col21, using the alias name Col21.
     * @return the value of Col21
     */
    public String getCol21() {
        return (String) getAttributeInternal(COL21);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col21.
     * @param value value to set the Col21
     */
    public void setCol21(String value) {
        setAttributeInternal(COL21, value);
    }

    /**
     * Gets the attribute value for Col22, using the alias name Col22.
     * @return the value of Col22
     */
    public String getCol22() {
        return (String) getAttributeInternal(COL22);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col22.
     * @param value value to set the Col22
     */
    public void setCol22(String value) {
        setAttributeInternal(COL22, value);
    }

    /**
     * Gets the attribute value for Col23, using the alias name Col23.
     * @return the value of Col23
     */
    public String getCol23() {
        return (String) getAttributeInternal(COL23);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col23.
     * @param value value to set the Col23
     */
    public void setCol23(String value) {
        setAttributeInternal(COL23, value);
    }

    /**
     * Gets the attribute value for Col24, using the alias name Col24.
     * @return the value of Col24
     */
    public String getCol24() {
        return (String) getAttributeInternal(COL24);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col24.
     * @param value value to set the Col24
     */
    public void setCol24(String value) {
        setAttributeInternal(COL24, value);
    }

    /**
     * Gets the attribute value for Col25, using the alias name Col25.
     * @return the value of Col25
     */
    public String getCol25() {
        return (String) getAttributeInternal(COL25);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col25.
     * @param value value to set the Col25
     */
    public void setCol25(String value) {
        setAttributeInternal(COL25, value);
    }

    /**
     * Gets the attribute value for Col26, using the alias name Col26.
     * @return the value of Col26
     */
    public String getCol26() {
        return (String) getAttributeInternal(COL26);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col26.
     * @param value value to set the Col26
     */
    public void setCol26(String value) {
        setAttributeInternal(COL26, value);
    }

    /**
     * Gets the attribute value for Col27, using the alias name Col27.
     * @return the value of Col27
     */
    public String getCol27() {
        return (String) getAttributeInternal(COL27);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col27.
     * @param value value to set the Col27
     */
    public void setCol27(String value) {
        setAttributeInternal(COL27, value);
    }

    /**
     * Gets the attribute value for Col28, using the alias name Col28.
     * @return the value of Col28
     */
    public String getCol28() {
        return (String) getAttributeInternal(COL28);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col28.
     * @param value value to set the Col28
     */
    public void setCol28(String value) {
        setAttributeInternal(COL28, value);
    }

    /**
     * Gets the attribute value for Col29, using the alias name Col29.
     * @return the value of Col29
     */
    public String getCol29() {
        return (String) getAttributeInternal(COL29);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col29.
     * @param value value to set the Col29
     */
    public void setCol29(String value) {
        setAttributeInternal(COL29, value);
    }

    /**
     * Gets the attribute value for Col30, using the alias name Col30.
     * @return the value of Col30
     */
    public Timestamp getCol30() {
        return (Timestamp) getAttributeInternal(COL30);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col30.
     * @param value value to set the Col30
     */
    public void setCol30(Timestamp value) {
        setAttributeInternal(COL30, value);
    }

    /**
     * Gets the attribute value for Col31, using the alias name Col31.
     * @return the value of Col31
     */
    public Timestamp getCol31() {
        return (Timestamp) getAttributeInternal(COL31);
    }

    /**
     * Sets <code>value</code> as the attribute value for Col31.
     * @param value value to set the Col31
     */
    public void setCol31(Timestamp value) {
        setAttributeInternal(COL31, value);
    }

    /**
     * Gets the attribute value for Flowcode, using the alias name Flowcode.
     * @return the value of Flowcode
     */
    public String getFlowcode() {
        return (String) getAttributeInternal(FLOWCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Flowcode.
     * @param value value to set the Flowcode
     */
    public void setFlowcode(String value) {
        setAttributeInternal(FLOWCODE, value);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String id) {
        return new Key(new Object[] { id });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.iocl.customer.model.entityobject.LevelDDataEo");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("KYC_CONNECTION_SEQ",getDBTransaction());
        setId(seq.getSequenceNumber().toString());
    }
}

